name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
        - 2.2.10
        - 2.3.8
        - 2.4.6
        - 2.5.5
        - 2.6.3
        - jruby-9.2.11.1

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rspec

  test-jruby:
    name: test (jruby-1.7.27)
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      uses: docker://jruby:1.7.27
      with:
        args: /bin/sh -c "bundle install && bundle exec rspec"
